import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import'./style.css';

const seed=[
{id:'alizeti',name:'Alizeti Sunflower Factory',kind:'Manufacturing',status:'Funding',capital:200000000,capex:118000000,fixed:24000000,price:7500,cost:4500,units:18000,pool:40,funded:55000000,desc:'Sunflower oil processing and seed-cake production.'},
{id:'western',name:'Western Pizza Point',kind:'Restaurant',status:'Operating',capital:75000000,capex:22000000,fixed:17700000,price:18500,cost:7000,units:2850,pool:25,funded:75000000,desc:'Operating restaurant with live margin and expansion planning.'}
];
const money=n=>{n=Number(n||0);if(Math.abs(n)>=1e9)return'TZS '+(n/1e9).toFixed(2)+'B';if(Math.abs(n)>=1e6)return'TZS '+(n/1e6).toFixed(n>=1e7?1:2)+'M';if(Math.abs(n)>=1e3)return'TZS '+(n/1e3).toFixed(1)+'K';return'TZS '+Math.round(n).toLocaleString()};
const pct=n=>Number(n||0).toFixed(1)+'%';
const calc=b=>{const revenue=b.price*b.units,variable=b.cost*b.units,gross=revenue-variable,profit=gross-b.fixed,annual=profit*12,margin=revenue?profit/revenue*100:0,be=b.price>b.cost?b.fixed/(b.price-b.cost):0,roi=b.capital?annual/b.capital*100:0,pay=profit>0?b.capital/profit:0;return{revenue,gross,profit,annual,margin,be,roi,pay}};
const share=(b,a)=>{const m=calc(b),capital=b.capital?a/b.capital:0,effective=capital*(b.pool/100),month=Math.max(0,m.profit)*effective,year=month*12;return{capital,effective,month,year,yield:a?year/a*100:0}};
const Metric=({label,value,tone})=><div className={'metric '+(tone||'')}><span>{label}</span><b>{value}</b></div>;
const Field=({label,value,onChange,moneyField})=><label className="field"><span>{label}</span><div className={moneyField?'moneyField':''}>{moneyField&&<i>TZS</i>}<input type="number" value={value} onChange={e=>onChange(Number(e.target.value))}/></div></label>;

function App(){
const[ready,setReady]=useState(false),[mode,setMode]=useState('admin'),[tab,setTab]=useState('overview'),[dark,setDark]=useState(false),[biz,setBiz]=useState(seed),[selected,setSelected]=useState('alizeti'),[amount,setAmount]=useState(5000000),[show,setShow]=useState(false),[toast,setToast]=useState('');
const[investments,setInvestments]=useState([{id:1,businessId:'alizeti',amount:5000000},{id:2,businessId:'western',amount:3000000}]);
useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('wizrac-v1')||'null');if(x){x.biz&&setBiz(x.biz);x.investments&&setInvestments(x.investments);typeof x.dark==='boolean'&&setDark(x.dark)}}catch{}setReady(true)},[]);
useEffect(()=>{if(ready)localStorage.setItem('wizrac-v1',JSON.stringify({biz,investments,dark}))},[ready,biz,investments,dark]);
if(!ready)return<div className="loading">Wizrac</div>;
const current=biz.find(x=>x.id===selected)||biz[0],update=(id,p)=>setBiz(xs=>xs.map(x=>x.id===id?Object.assign({},x,p):x)),note=t=>{setToast(t);setTimeout(()=>setToast(''),1800)};
const switchMode=m=>{setMode(m);setTab(m==='admin'?'overview':'home')};
const nav=mode==='admin'?[['overview','⌂','Overview'],['business','◇','Businesses'],['scenario','↗','Scenario Lab'],['investors','◎','Investors']]:[['home','⌂','Home'],['explore','◇','Explore'],['portfolio','◌','Portfolio']];
let body;
if(mode==='admin'&&tab==='overview')body=<Overview biz={biz} open={id=>{setSelected(id);setTab('business')}} add={()=>setShow(true)}/>;
if(mode==='admin'&&tab==='business')body=<Business biz={biz} current={current} select={setSelected} update={update} add={()=>setShow(true)}/>;
if(mode==='admin'&&tab==='scenario')body=<Scenario biz={biz} current={current} select={setSelected} update={update}/>;
if(mode==='admin'&&tab==='investors')body=<Investors investments={investments} biz={biz}/>;
if(mode==='investor'&&tab==='home')body=<InvestorHome biz={biz} investments={investments} open={id=>{setSelected(id);setTab('explore')}}/>;
if(mode==='investor'&&tab==='explore')body=<Explore biz={biz} current={current} select={setSelected} amount={amount} setAmount={setAmount} invest={(b,a)=>{setInvestments(x=>x.concat({id:Date.now(),businessId:b.id,amount:a}));update(b.id,{funded:b.funded+a});note('Demo investment added')}}/>;
if(mode==='investor'&&tab==='portfolio')body=<Portfolio investments={investments} biz={biz}/>;
return<div className={dark?'app dark':'app'}>
<aside><button className="brand" onClick={()=>setTab(mode==='admin'?'overview':'home')}><em>W</em><span><b>Wizrac</b><small>Capital OS</small></span></button><div className="switch"><button className={mode==='admin'?'on':''} onClick={()=>switchMode('admin')}>Admin</button><button className={mode==='investor'?'on':''} onClick={()=>switchMode('investor')}>Investor</button></div><nav>{nav.map(n=><button key={n[0]} className={tab===n[0]?'active':''} onClick={()=>setTab(n[0])}><i>{n[1]}</i>{n[2]}</button>)}</nav><div className="foot"><button className="theme" onClick={()=>setDark(!dark)}>{dark?'☀ Light mode':'☾ Dark mode'}</button><div className="profile"><span>W</span><div><b>Wizrac</b><small>Demo workspace</small></div></div></div></aside>
<main><header><b className="mobileBrand">Wizrac</b><div><span className="demo">Interactive demo · local data</span><button className="round" onClick={()=>setDark(!dark)}>{dark?'☀':'☾'}</button><span className="avatar">W</span></div></header>{body}</main>
<div className="bottom">{nav.map(n=><button key={n[0]} className={tab===n[0]?'active':''} onClick={()=>setTab(n[0])}><b>{n[1]}</b><small>{n[2]}</small></button>)}</div>
{show&&<Create close={()=>setShow(false)} create={b=>{setBiz(x=>x.concat(b));setSelected(b.id);setShow(false);setTab('business');note('Business created')}}/>}{toast&&<div className="toast">{toast}</div>}
</div>
}

function Card({b,onClick}){const m=calc(b),progress=Math.min(100,b.funded/b.capital*100);return<button className="bizCard" onClick={onClick}><div className="cardTop"><span className="icon">{b.kind==='Restaurant'?'●':'✦'}</span><span className={b.status==='Operating'?'pill live':'pill'}>{b.status}</span></div><h3>{b.name}</h3><p>{b.desc}</p><div className="pair"><div><small>Revenue / mo.</small><b>{money(m.revenue)}</b></div><div><small>Operating profit</small><b>{money(m.profit)}</b></div></div><div className="progress"><i style={{width:progress+'%'}}/></div><footer><span>{pct(progress)} funded</span><b>{money(b.capital)}</b></footer></button>}

function Overview({biz,open,add}){const revenue=biz.reduce((a,b)=>a+calc(b).revenue,0),profit=biz.reduce((a,b)=>a+calc(b).profit,0);return<section className="page"><div className="pageHead"><div><span className="kicker">Business command center</span><h1>Good afternoon.</h1><p>Run the businesses, model expansion and understand every shilling.</p></div><button className="primary" onClick={add}>＋ New business</button></div><div className="hero"><div className="heroCard"><span>Combined monthly revenue</span><strong>{money(revenue)}</strong><p>{biz.length} businesses in the demo workspace</p><div className="bars">{[28,42,38,56,61,70,67,86].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div></div><div className="health"><span className="kicker">Portfolio health</span><h2>{profit>=0?'Profitable':'Needs attention'}</h2><p>Based on current selling prices, unit costs and overhead.</p><div><Metric label="Monthly profit" value={money(profit)} tone={profit>=0?'green':'red'}/><Metric label="Businesses" value={String(biz.length)}/></div></div></div><div className="sectionTitle"><span><small className="kicker">Your businesses</small><h2>Operate. Improve. Raise.</h2></span></div><div className="cards">{biz.map(b=><Card key={b.id} b={b} onClick={()=>open(b.id)}/>)}</div></section>}

function Business({biz,current,select,update,add}){const m=calc(current);return<section className="page"><div className="pageHead compact"><div><span className="kicker">Business management</span><h1>{current.name}</h1><p>Edit the inputs. Every number recalculates instantly.</p></div><button className="ghost" onClick={add}>＋ Add business</button></div><Tabs biz={biz} current={current} select={select}/><div className="two"><div className="panel"><div className="panelHead"><span><small className="kicker">Operating inputs</small><h2>Business model</h2></span><small className="auto">Live calculation</small></div><div className="formGrid"><Field label="Capital target" value={current.capital} moneyField onChange={v=>update(current.id,{capital:v})}/><Field label="Capital expenditure" value={current.capex} moneyField onChange={v=>update(current.id,{capex:v})}/><Field label="Monthly fixed expenses" value={current.fixed} moneyField onChange={v=>update(current.id,{fixed:v})}/><Field label="Selling price / unit" value={current.price} moneyField onChange={v=>update(current.id,{price:v})}/><Field label="Variable cost / unit" value={current.cost} moneyField onChange={v=>update(current.id,{cost:v})}/><Field label="Units / month" value={current.units} onChange={v=>update(current.id,{units:v})}/></div><div className="pool"><div><span>Investor profit pool</span><b>{current.pool}%</b></div><input type="range" min="0" max="100" value={current.pool} onChange={e=>update(current.id,{pool:Number(e.target.value)})}/><small>Share of distributable profit assigned to the investor pool in this demo structure.</small></div></div><div className="panel"><div className="panelHead"><span><small className="kicker">Economics</small><h2>Live performance</h2></span></div><div className="metrics"><Metric label="Monthly revenue" value={money(m.revenue)}/><Metric label="Operating profit" value={money(m.profit)} tone={m.profit>=0?'green':'red'}/><Metric label="Operating margin" value={pct(m.margin)}/><Metric label="Break-even units" value={Math.ceil(m.be).toLocaleString()}/><Metric label="Annual profit" value={money(m.annual)}/><Metric label="Project ROI" value={pct(m.roi)}/><Metric label="Capital payback" value={m.pay?m.pay.toFixed(1)+' mo.':'—'}/><Metric label="Profit pool" value={current.pool+'%'}/></div><div className="insight"><b>{m.profit>=0?'Healthy unit economics':'Margin warning'}</b><p>{m.profit>=0?'At current assumptions this business generates '+money(m.profit)+' in estimated monthly operating profit.':'Costs currently exceed gross contribution. Use Scenario Lab to test changes.'}</p></div></div></div><AdminCalc b={current}/></section>}

function AdminCalc({b}){const[a,setA]=useState(5000000),s=share(b,a);return<div className="panel calc"><div className="panelHead"><span><small className="kicker">Capital calculator</small><h2>What does an investor receive?</h2></span></div><div className="calcGrid"><div><label>Investment amount</label><div className="amount"><span>TZS</span><input type="number" value={a} onChange={e=>setA(Number(e.target.value))}/></div><div className="quick">{[1,5,10,20,50].map(x=><button key={x} onClick={()=>setA(x*1000000)}>{x}M</button>)}</div></div><div className="allocation"><div><span>Capital pool share</span><b>{pct(s.capital*100)}</b></div><div><span>Effective profit entitlement</span><b>{pct(s.effective*100)}</b></div><div><span>Est. monthly distribution</span><b>{money(s.month)}</b></div><div><span>Est. annual distribution</span><b>{money(s.year)}</b></div><div><span>Illustrative cash yield</span><b>{pct(s.yield)}</b></div></div></div></div>}

function Tabs({biz,current,select}){return<div className="tabs">{biz.map(b=><button key={b.id} className={b.id===current.id?'on':''} onClick={()=>select(b.id)}>{b.name}</button>)}</div>}

function Scenario({biz,current,select,update}){const m=calc(current),sliders=[['Selling price',current.price,Math.max(500,current.price*.5),current.price*1.6,500,'price',money],['Monthly units',current.units,Math.max(10,current.units*.3),current.units*2,10,'units',v=>Math.round(v).toLocaleString()],['Unit cost',current.cost,Math.max(100,current.cost*.5),current.cost*1.6,100,'cost',money],['Fixed costs',current.fixed,0,current.fixed*1.7,100000,'fixed',money]];return<section className="page"><div className="pageHead compact"><div><span className="kicker">Scenario lab</span><h1>Move one lever. See the business change.</h1><p>Test price, volume and cost decisions before spending money.</p></div></div><Tabs biz={biz} current={current} select={select}/><div className="scenario"><div className="panel">{sliders.map(s=><div className="slider" key={s[0]}><div><span>{s[0]}</span><b>{s[6](s[1])}</b></div><input type="range" min={s[2]} max={s[3]} step={s[4]} value={s[1]} onChange={e=>update(current.id,{[s[5]]:Number(e.target.value)})}/></div>)}</div><div className="result"><small className="kicker">Projected monthly operating profit</small><strong>{money(m.profit)}</strong><p>{pct(m.margin)} operating margin</p><div className="bars big">{[36,47,42,58,66,71,79,91].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div><div className="resultRows"><div><span>Revenue</span><b>{money(m.revenue)}</b></div><div><span>Annual profit</span><b>{money(m.annual)}</b></div><div><span>Break-even</span><b>{Math.ceil(m.be).toLocaleString()} units</b></div><div><span>ROI</span><b>{pct(m.roi)}</b></div></div></div></div></section>}

function Investors({investments,biz}){const total=investments.reduce((a,x)=>a+x.amount,0);return<section className="page"><div className="pageHead compact"><div><span className="kicker">Investor desk</span><h1>Capital register.</h1><p>Demo commitments made from Investor mode appear here immediately.</p></div></div><div className="stats"><Metric label="Demo capital committed" value={money(total)}/><Metric label="Commitments" value={String(investments.length)}/><Metric label="Businesses" value={String(new Set(investments.map(x=>x.businessId)).size)}/><Metric label="Backend" value="Not connected"/></div><div className="panel table"><div className="row head"><span>Investor</span><span>Business</span><span>Capital</span><span>Profit entitlement</span></div>{investments.map(x=>{const b=biz.find(b=>b.id===x.businessId),s=b?share(b,x.amount):null;return b&&<div className="row" key={x.id}><span><b>Demo Investor</b><small>Local record</small></span><span>{b.name}</span><span>{money(x.amount)}</span><span>{pct(s.effective*100)}</span></div>})}</div></section>}

function InvestorHome({biz,investments,open}){const total=investments.reduce((a,x)=>a+x.amount,0),annual=investments.reduce((a,x)=>{const b=biz.find(b=>b.id===x.businessId);return a+(b?share(b,x.amount).year:0)},0);return<section className="page"><div className="welcome"><small>Wizrac investor demo</small><h1>Your capital, clearly.</h1><p>Explore a business, model an amount and see exactly how the profit entitlement is calculated.</p><strong>{money(total)}</strong><span>demo capital committed</span><button onClick={()=>open(biz[0].id)}>Explore opportunities →</button></div><div className="stats"><Metric label="Demo capital" value={money(total)}/><Metric label="Est. annual distributions" value={money(annual)} tone="green"/><Metric label="Positions" value={String(investments.length)}/><Metric label="Storage" value="This device"/></div><div className="cards">{biz.map(b=><Card key={b.id} b={b} onClick={()=>open(b.id)}/>)}</div></section>}

function Explore({biz,current,select,amount,setAmount,invest}){const m=calc(current),s=share(current,amount),progress=Math.min(100,current.funded/current.capital*100);return<section className="page"><div className="pageHead compact"><div><span className="kicker">Explore</span><h1>{current.name}</h1><p>{current.desc}</p></div></div><Tabs biz={biz} current={current} select={select}/><div className="investGrid"><div className="panel project"><span className={current.status==='Operating'?'pill live':'pill'}>{current.status}</span><h2>{current.name}</h2><p>{current.desc}</p><div className="stats"><Metric label="Monthly revenue" value={money(m.revenue)}/><Metric label="Operating profit" value={money(m.profit)} tone="green"/><Metric label="Capital target" value={money(current.capital)}/><Metric label="Investor profit pool" value={current.pool+'%'}/></div><div className="progress"><i style={{width:progress+'%'}}/></div><small>{money(current.funded)} of {money(current.capital)} demo-funded</small></div><div className="panel investBox"><small className="kicker">Investment calculator</small><h2>Model your amount</h2><div className="amount"><span>TZS</span><input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></div><div className="quick four">{[1,5,10,20].map(x=><button key={x} onClick={()=>setAmount(x*1000000)}>{x}M</button>)}</div><div className="allocation light"><div><span>Capital pool share</span><b>{pct(s.capital*100)}</b></div><div><span>Profit entitlement</span><b>{pct(s.effective*100)}</b></div><div><span>Est. monthly distribution</span><b>{money(s.month)}</b></div><div><span>Est. annual distribution</span><b>{money(s.year)}</b></div></div><button className="primary full" onClick={()=>invest(current,amount)}>Add demo investment</button><small className="fine">Demo only. No payment is collected.</small></div></div></section>}

function Portfolio({investments,biz}){const rows=investments.map((x,i)=>{const b=biz.find(b=>b.id===x.businessId);return b?{...x,b,s:share(b,x.amount),i}:null}).filter(Boolean),total=rows.reduce((a,x)=>a+x.amount,0),annual=rows.reduce((a,x)=>a+x.s.year,0);return<section className="page"><div className="pageHead compact"><div><span className="kicker">Portfolio</span><h1>Your positions.</h1><p>Every demo commitment and its calculated share.</p></div></div><div className="stats"><Metric label="Capital committed" value={money(total)}/><Metric label="Est. annual distributions" value={money(annual)} tone="green"/><Metric label="Weighted yield" value={pct(total?annual/total*100:0)}/><Metric label="Positions" value={String(rows.length)}/></div><div className="panel table"><div className="row head"><span>Business</span><span>Capital</span><span>Profit entitlement</span><span>Est. annual</span></div>{rows.map(r=><div className="row" key={r.i}><span><b>{r.b.name}</b><small>{r.b.kind}</small></span><span>{money(r.amount)}</span><span>{pct(r.s.effective*100)}</span><span>{money(r.s.year)}</span></div>)}</div></section>}

function Create({close,create}){const[f,setF]=useState({name:'',kind:'New venture',capital:100000000,capex:50000000,fixed:10000000,price:10000,cost:5000,units:3000,pool:35,funded:0,desc:''});const set=(k,v)=>setF(Object.assign({},f,{[k]:v}));return<div className="modalWrap" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><span><small className="kicker">New business</small><h2>Build the model</h2></span><button onClick={close}>×</button></div><div className="formGrid"><label className="field"><span>Business name</span><div><input value={f.name} onChange={e=>set('name',e.target.value)}/></div></label><label className="field"><span>Category</span><div><input value={f.kind} onChange={e=>set('kind',e.target.value)}/></div></label><Field label="Capital target" value={f.capital} moneyField onChange={v=>set('capital',v)}/><Field label="Capital expenditure" value={f.capex} moneyField onChange={v=>set('capex',v)}/><Field label="Monthly fixed expenses" value={f.fixed} moneyField onChange={v=>set('fixed',v)}/><Field label="Selling price / unit" value={f.price} moneyField onChange={v=>set('price',v)}/><Field label="Variable cost / unit" value={f.cost} moneyField onChange={v=>set('cost',v)}/><Field label="Units / month" value={f.units} onChange={v=>set('units',v)}/><Field label="Investor profit pool %" value={f.pool} onChange={v=>set('pool',v)}/></div><label className="field desc"><span>Description</span><div><input value={f.desc} onChange={e=>set('desc',e.target.value)}/></div></label><div className="actions"><button className="ghost" onClick={close}>Cancel</button><button className="primary" onClick={()=>f.name.trim()&&create(Object.assign({},f,{id:'b-'+Date.now(),status:'Funding'}))}>Create business</button></div></div></div>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
